server:
  port: 8005
  servlet:
    context-path: /website
  tomcat:
    uri-encoding: UTF-8
    max-http-post-size: -1
    max-http-header-size: 102400

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/website?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: root
    password: ZhenYouQian888!
#    url: jdbc:mysql://127.0.0.1:3306/website?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
#    username: admin
#    password: Cui123456!
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙，此处是filter修改的地方
    filters:
      commons-log.connection-logger-name: stat,wall,log4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true

  redis:
    # Redis数据库索引（默认为0）
    database: 10
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 200
        # 连接池中的最大空闲连接
        max-idle: 20
        # 连接池中的最小空闲连接
        min-idle: 10
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
    # 连接超时时间（毫秒）默认是2000ms
    timeout: 2000ms

#  mvc:
#    static-path-pattern: /resources/**
#  resources:
#    static-locations: classpath:/static/,classpath:/public,classpath:/resources/,classpath:/META-INF/resources,file:K:\resources/,file:H:\COVER/
#      ,file:I:\resource/,file:H:\resources/,file:N:\resources/,file:H:\电视剧/

  #    classpath:/static,classpath:/public,classpath:/resources,classpath:/META-INF/resources,

  rabbitmq:
    host: 192.168.1.14
    port: 5672
    virtual-host: my_vhost
    username: root
    password: 123456
    listener:
      simple:
        prefetch: 0
        auto-startup: false
      direct:
        auto-startup: false

mybatis:
  configuration:
    map-underscore-to-camel-case: true #开启驼峰映射
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    #打印SQL信息
    com.intehel.dao: debug
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

file:
  url:
#    prefix: http://www.caesium.top:5003/website/resources
    prefix: http://192.168.1.14:5003/

rabbitmq:
  start: false

sysType:
  type: remote
  remoteUrl: http://47.99.153.52:8005/website/
  innerUrl: 192.168.1.14