package com.cxy.website.dao.sys.sqlprovider;

import com.cxy.website.model.sys.SysRole;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.jdbc.SQL;

public class SysRoleSqlProvider {
    public StringBuilder findRole(@Param("roleName") String roleName){
        StringBuilder sql = new StringBuilder();
        sql.append( "select * from tb_sys_role where is_del='0'");
        sql.append(panduantiaojian(roleName));
        return sql;
    }
    public StringBuilder countRoleList(@Param("role") String role){
        StringBuilder sql = new StringBuilder();
        sql.append( "select count(id)from tb_sys_role where is_del='0'");
        sql.append(panduantiaojian(role));
        return sql;
    }
    public StringBuilder panduantiaojian(String roleName){
        StringBuilder sql = new StringBuilder();
        if(roleName != null && roleName != ""){
            sql.append(" AND role_name like '%"+roleName +"%'");
        }
        return sql;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_role
     *
     * @mbg.generated
     */
    public String insertSelective(SysRole record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("tb_sys_role");
        
        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getRoleName() != null) {
            sql.VALUES("role_name", "#{roleName,jdbcType=VARCHAR}");
        }
        
        if (record.getDescription() != null) {
            sql.VALUES("description", "#{description,jdbcType=VARCHAR}");
        }
        
        if (record.getIsDel() != null) {
            sql.VALUES("is_del", "#{isDel,jdbcType=INTEGER}");
        }
        
        if (record.getCreateTime() != null) {
            sql.VALUES("create_time", "#{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getRemark() != null) {
            sql.VALUES("remark", "#{remark,jdbcType=VARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_role
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(SysRole record) {
        SQL sql = new SQL();
        sql.UPDATE("tb_sys_role");
        
        if (record.getRoleName() != null) {
            sql.SET("role_name = #{roleName,jdbcType=VARCHAR}");
        }
        
        if (record.getDescription() != null) {
            sql.SET("description = #{description,jdbcType=VARCHAR}");
        }
        
        if (record.getIsDel() != null) {
            sql.SET("is_del = #{isDel,jdbcType=INTEGER}");
        }
        
        if (record.getCreateTime() != null) {
            sql.SET("create_time = #{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getRemark() != null) {
            sql.SET("remark = #{remark,jdbcType=VARCHAR}");
        }
        
        sql.WHERE("id = #{id,jdbcType=INTEGER}");
        
        return sql.toString();
    }
}