package com.cxy.website.dao.sys.sqlprovider;

import com.cxy.website.model.sys.SysRoleMenu;
import org.apache.ibatis.jdbc.SQL;

public class SysRoleMenuSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_role_menu
     *
     * @mbg.generated
     */
    public String insertSelective(SysRoleMenu record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("tb_sys_role_menu");
        
        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getRoleId() != null) {
            sql.VALUES("role_id", "#{roleId,jdbcType=INTEGER}");
        }
        
        if (record.getMenuId() != null) {
            sql.VALUES("menu_id", "#{menuId,jdbcType=INTEGER}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_role_menu
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(SysRoleMenu record) {
        SQL sql = new SQL();
        sql.UPDATE("tb_sys_role_menu");
        
        if (record.getRoleId() != null) {
            sql.SET("role_id = #{roleId,jdbcType=INTEGER}");
        }
        
        if (record.getMenuId() != null) {
            sql.SET("menu_id = #{menuId,jdbcType=INTEGER}");
        }
        
        sql.WHERE("id = #{id,jdbcType=INTEGER}");
        
        return sql.toString();
    }
}