package com.cxy.website.dao.sys;

import com.cxy.website.dao.sys.sqlprovider.SysUserSqlProvider;
import com.cxy.website.model.sys.SysUser;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;
import org.springframework.cache.annotation.*;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
public interface SysUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_user
     *
     * @mbg.generated
     */
    @Delete({
        "delete from tb_sys_user",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    @CacheEvict
    int deleteByPrimaryKey(Integer id);
    /**
     *@Description 分页条件查询用户信息
     *@Param
     *@Return
     *@Author 侯森林
     *@Date 2019-9-18
     */
    @SelectProvider(type = SysUserSqlProvider.class, method = "findUser")
    @Cacheable
    List<SysUser> findUser(@Param("userName") String userName,
                           @Param("sex") Integer sex,
                           @Param("age") Integer age,
                           @Param("beginDate") String beginDate,
                           @Param("endDate") String endDate);
    /**
     *@Description 返回分页条件查询用户数量信息
     *@Param
     *@Return
     *@Author 侯森林
     *@Date 2019-9-18
     */
    @SelectProvider(type = SysUserSqlProvider.class, method = "countUserList")
    @Cacheable
    Integer countUserList(@Param("userName") String userName,
                          @Param("sex") Integer sex,
                          @Param("age") Integer age,
                          @Param("beginDate") String beginDate,
                          @Param("endDate") String endDate);

    @Select("select * from tb_sys_user where user_name=#{userName} and is_del='0' ")
    @Cacheable
    SysUser findUserByUserName(String userName);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_user
     *
     * @mbg.generated
     */
    @InsertProvider(type= SysUserSqlProvider.class, method="insertSelective")
    @CachePut
    int insertSelective(SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_user
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, email,name, password, salt, state, tel, user_name, age, sex, ",
        "ip_limit, create_time, creater, is_del,remark",
        "from tb_sys_user",
        "where id = #{id,jdbcType=INTEGER} and is_del='0'"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="email", property="email", jdbcType=JdbcType.VARCHAR),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="password", property="password", jdbcType=JdbcType.VARCHAR),
        @Result(column="salt", property="salt", jdbcType=JdbcType.VARCHAR),
        @Result(column="state", property="state", jdbcType=JdbcType.TINYINT),
        @Result(column="tel", property="tel", jdbcType=JdbcType.VARCHAR),
        @Result(column="user_name", property="userName", jdbcType=JdbcType.VARCHAR),
        @Result(column="age", property="age", jdbcType=JdbcType.INTEGER),
        @Result(column="sex", property="sex", jdbcType=JdbcType.INTEGER),
        @Result(column="ip_limit", property="ipLimit", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="creater", property="creater", jdbcType=JdbcType.INTEGER),
        @Result(column="remark", property="remark", jdbcType=JdbcType.VARCHAR)
    })
    @Cacheable
    SysUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_user
     *
     * @mbg.generated
     */
    @UpdateProvider(type=SysUserSqlProvider.class, method="updateByPrimaryKeySelective")
    @CachePut
    int updateByPrimaryKeySelective(SysUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_sys_user
     *
     * @mbg.generated
     */
    @Update({
        "update tb_sys_user",
        "set email = #{email,jdbcType=VARCHAR},",
          "name = #{name,jdbcType=VARCHAR},",
          "password = #{password,jdbcType=VARCHAR},",
          "salt = #{salt,jdbcType=VARCHAR},",
          "state = #{state,jdbcType=TINYINT},",
          "tel = #{tel,jdbcType=VARCHAR},",
          "user_name = #{userName,jdbcType=VARCHAR},",
          "age = #{age,jdbcType=INTEGER},",
          "sex = #{sex,jdbcType=INTEGER},",
            "is_del = #{isDel,jdbcType=INTEGER},",
          "ip_limit = #{ipLimit,jdbcType=VARCHAR},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "creater = #{creater,jdbcType=INTEGER},",
          "remark = #{remark,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @CachePut
    int updateByPrimaryKey(SysUser record);
}