package com.cxy.website.dao.sys;

import com.cxy.website.dao.sys.sqlprovider.UserRoleSqlProvider;
import com.cxy.website.model.sys.UserRole;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;
import org.springframework.cache.annotation.*;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
public interface UserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_role
     *
     * @mbg.generated
     */
    @Delete({
        "delete from tb_user_role",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    @CacheEvict
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_role
     *
     * @mbg.generated
     */
    @Insert({
        "insert into tb_user_role (ID, ROLE_ID, ",
        "USER_ID)",
        "values (#{id,jdbcType=INTEGER}, #{roleId,jdbcType=INTEGER}, ",
        "#{userId,jdbcType=INTEGER})"
    })
    @CachePut
    int insert(UserRole record);

    @Select("select role_id from tb_user_role where user_id=#{userId}")
    @Cacheable
    List<Integer> getRoleIdList(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_role
     *
     * @mbg.generated
     */
    @InsertProvider(type= UserRoleSqlProvider.class, method="insertSelective")
    @CachePut
    int insertSelective(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_role
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "ID, ROLE_ID, USER_ID",
        "from tb_user_role",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="ID", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="ROLE_ID", property="roleId", jdbcType=JdbcType.INTEGER),
        @Result(column="USER_ID", property="userId", jdbcType=JdbcType.INTEGER)
    })
    @Cacheable
    UserRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_role
     *
     * @mbg.generated
     */
    @UpdateProvider(type=UserRoleSqlProvider.class, method="updateByPrimaryKeySelective")
    @CachePut
    int updateByPrimaryKeySelective(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user_role
     *
     * @mbg.generated
     */
    @Update({
        "update tb_user_role",
        "set ROLE_ID = #{roleId,jdbcType=INTEGER},",
          "USER_ID = #{userId,jdbcType=INTEGER}",
        "where ID = #{id,jdbcType=INTEGER}"
    })
    @CachePut
    int updateByPrimaryKey(UserRole record);

    @Delete("delete from tb_user_role where user_id=#{userId}")
    @CacheEvict
    void deleteUserRole(Integer userId);

    @Insert("<script>"  +
            "INSERT INTO tb_user_role(role_id,user_id) "
            + "VALUES <foreach collection=\"list\" item=\"item\" index=\"index\" separator=\",\">" +
            "(#{item.roleId},#{item.userId})" +
            " </foreach>"
            + "</script>")
    @CachePut
    void insertUserRole(List<UserRole> list);


}